baseURL = "https://stanislawlem.cz/"
defaultContentLanguage = "cs"
title = "Stanislaw Lem"
theme = "PaperMod"

enableRobotsTXT = true
buildDrafts = false
buildFuture = false

[languages.cs] 
  locale = "cs-CZ"
  languageName = "Čeština"

[pagination]
  pagerSize = 12

[[menu.main]]
  identifier = "books"
  name = "Knihy"
  url = "/books/"
  weight = 10 

[[menu.main]]
  identifier = "posts"
  name = "Články"
  url = "/posts/"
  weight = 20

[[menu.main]]
  identifier = "about"
  name = "O stránce"
  url = "/about/"
  weight = 30

[params]
  env = "production"
  description = "Stanislaw Lem v CZ, moje sbírka jeho knih, zážitky ze čtení a další související věci."
  author = "Lukas"
  defaultTheme = "auto"
  ShowReadingTime = true
  ShowShareButtons = false
  ShowPostNavLinks = true
  ShowBreadCrumbs = true
  ShowCodeCopyButtons = true
  ShowWordCount = false
  ShowToc = false
  disableSpecial1stPost = true
  mainSections = ["posts"]


  [params.homeInfoParams]
    Title = "Vítejte"
    Content = "Stanislaw Lem v CZ, moje sbírka jeho knih, zážitky ze čtení a další související věci. Mrkněte na [sbírku](/books/) nebo na [články](/posts/)."

[taxonomies]
  tag = "tags"
  genre = "genres"
  author = "authors"

[markup.goldmark.renderer]
  unsafe = true